trigger:
  branches:
    include:
      - master

pool:
  name: "angularlinux"

variables:
  - group: angularGroup
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: "Install Node.js"

  - script:
      npm install
    displayName: "Install"

  - script:
      npm run build
    displayName: "Build Application"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.SourcesDirectory)/dist/angular-social-network"
      artifactName: "angular-artifacts"
      publishLocation: "Container"

  - task: Docker@2
    inputs:
      containerRegistry: $(containerRegistry)
      repository: $(repository)
      command: "buildAndPush"
      Dockerfile: $(dockerfile)
    displayName: "Build and Push Docker Image $(dockerfile) $(containerRegistry) $(repository)"
