trigger:
  branches:
    include:
      - main  # Or whichever branch you want to trigger the pipeline

pool:
  name: 'angular'  # Replace with the name of your self-hosted agent pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build
  displayName: 'Install Angular CLI and Build Application'

- task: Docker@2
  inputs:
    containerRegistry: 'docker'  # Replace with your container registry connection name
    repository: 'aftocr/angular'  # Replace with your Docker repository name
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(Build.BuildId)
  displayName: 'Build and Push Docker Image'
