trigger:
  branches:
    include:
      - master  

pool:
  name: 'angular'  

variables:
- group: angularGroup
steps:

- script: |
    npm install
    npm run build
  displayName: 'Install and Build Application'

- task: Docker@2
  inputs:
    containerRegistry: $(containerRegistry)  
    repository: $(repository)  
    command: 'buildAndPush'
    Dockerfile: $(dockerfile)
  displayName: 'Build and Push Docker Image $(dockerfile) $(containerRegistry) $(repository)'
